MATRIX_WIDTH = 128
MATRIX_HEIGHT = 32

ROLLING_AVERAGE_MAX = 4

SHOW_DEBUG = True
SHOW_ALL_DEBUG_LANDMARKS = True
FT_CAPTURE_WIDTH = 640
FT_CAPTURE_HEIGHT = 480

WINDOW_RENDER = True
WINDOW_RENDER_SCALE = 10