TOP_LIP_TOP_CENTER = 0
TOP_LIP_BOTTOM_CENTER = 1
BOTTOM_LIP_TOP_CENTER = 2
BOTTOM_LIP_BOTTOM_CENTER = 3

MOUTH_RIGHT_EDGE = 4
MOUTH_LEFT_EDGE = 5

RIGHT_EYE_CENTER = 6
RIGHT_EYE_TOP = 7
RIGHT_EYE_BOTTOM = 8
RIGHT_EYE_INNER = 9
RIGHT_EYE_OUTER = 10

RIGHT_EYE_LID_TOP = 11
RIGHT_EYE_LID_BOTTOM = 12

LEFT_EYE_CENTER = 13
LEFT_EYE_TOP = 14
LEFT_EYE_BOTTOM = 15
LEFT_EYE_INNER = 16
LEFT_EYE_OUTER = 17

LEFT_EYE_LID_TOP = 18
LEFT_EYE_LID_BOTTOM = 19

HEAD_LEFT_EDGE = 20
HEAD_RIGHT_EDGE = 21